namespace TiaAgent.Contracts.Errors;

/// <summary>
/// Structured error codes from ARCHITECTURE.md §17.
/// </summary>
public enum TiaErrorCode
{
    TIA_NOT_CONNECTED,
    TIA_PROJECT_NOT_OPEN,
    TIA_SESSION_EXPIRED,
    TIA_SELECTION_EXPIRED,
    TIA_OBJECT_NOT_FOUND,
    TIA_OBJECT_CHANGED,
    TIA_OPERATION_NOT_SUPPORTED,
    TIA_PERMISSION_DENIED,
    TIA_COMPILE_FAILED,
    TIA_IMPORT_FAILED,
    TIA_BUSY,
    TIA_TIMEOUT,
    TIA_CANCELLED,
    TIA_VERSION_INCOMPATIBLE,
    APPROVAL_REQUIRED,
    APPROVAL_EXPIRED,
    APPROVAL_ALREADY_USED,
    APPROVAL_SCOPE_MISMATCH,
    APPROVAL_DIFF_MISMATCH,
    CHANGE_SET_NOT_FOUND,
    CHANGE_SET_CHANGED,
    OPENCODE_UNAVAILABLE,
    OPENCODE_TASK_FAILED,
    MCP_AUTHENTICATION_FAILED,
    MCP_RATE_LIMITED,
    INVALID_REQUEST,
    PAYLOAD_TOO_LARGE,
    INTERNAL_ERROR
}
