using System.ComponentModel;
using ModelContextProtocol.Server;
using TiaAgent.Contracts.Abstractions;
using TiaAgent.Contracts.Dtos;
using TiaAgent.Contracts.Requests;

namespace TiaAgent.Mcp.Tools;

/// <summary>
/// MCP tool handlers for TIA context and selection operations.
/// Each handler is a thin adapter delegating to ITiaProjectService.
/// </summary>
[McpServerToolType]
public class TiaContextTools
{
    private readonly ITiaProjectService _projectService;

    public TiaContextTools(ITiaProjectService projectService)
    {
        _projectService = projectService;
    }

    [McpServerTool(Name = "tia_get_current_context", ReadOnly = true)]
    [Description("Returns the current TIA Portal session context including project name, version, PLC count, block count, and available capabilities.")]
    public Task<TiaContextDto> GetCurrentContext(CancellationToken cancellationToken)
    {
        return _projectService.GetCurrentContextAsync(cancellationToken);
    }

    [McpServerTool(Name = "tia_get_current_selection", ReadOnly = true)]
    [Description("Returns the immutable selection snapshot captured when a command was triggered. Requires a selectionToken provided by the Add-In.")]
    public Task<SelectionSnapshotDto> GetCurrentSelection(
        [Description("The selection token generated by the Add-In at command trigger time.")] string selectionToken,
        CancellationToken cancellationToken)
    {
        return _projectService.GetSelectionAsync(selectionToken, cancellationToken);
    }
}
